name: rtm_block_coding
version: 0.0.1
description: Block Coder for RTM
environment:
  sdk: '>=1.8.2 <2.0.0'
dependencies:
  browser: any
  polymer: any
  paper_elements: any
  core_elements: any
  http: any
  xml_rpc: any
  xml : any
  wasanbon_xmlrpc:
    git : https://github.com/sugarsweetrobotics/wasanbon_xmlrpc.dart
  rtcprofile:
    git : https://github.com/sugarsweetrobotics/rtcprofile.dart
  shape:
    git : https://github.com/sugarsweetrobotics/shape.dart
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points:
    - web/index.html
- $dart2js:
    $include: web/index.html_bootstrap.dart
