name: rtm_block_coding
version: 0.0.1
description: Block Coder for RTM
environment:
  sdk: '>=1.8.2 <2.0.0'
dependencies:
  browser: any
  polymer: any
  paper_elements: any
  core_elements: any
  http: any
  xml_rpc: any
  xml : any
  web_components: '>=0.11.3 <0.13.0'
  wasanbon_xmlrpc:
    git : git://github.com/sugarsweetrobotics/wasanbon_xmlrpc.dart
  rtcprofile:
    git : git://github.com/sugarsweetrobotics/rtcprofile.dart
  shape:
    git : git://github.com/sugarsweetrobotics/shape.dart
dev_dependencies:
  unittest: any
transformers:

#- web_components:
#    entry_points:
#    - web/index.html
- polymer:
    entry_points:
    - web/index.html
- $dart2js:
    #$include: web/index.html_bootstrap.dart
    $include: 'web/index.html.polymer.bootstrap.dart'